# <https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll>
# <https://jekyllrb.com/docs/configuration/>
# <https://jekyllrb.com/docs/front-matter/>
# <https://jekyllrb.com/docs/variables/>
# <https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site>
# lsi: false
# safe: true
# # source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
